apiVersion: v1
kind: Service
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels: {{ include "newrelic-php-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector: {{- include "newrelic-php-agent.selectorLabels" . | nindent 4 }}
