apiVersion: v2
name: newrelic-php-agent
description: A Helm chart to deploy the New Relic PHP Agent.
type: application
version: 0.1.2
appVersion: "0.1.2"
dependencies:
  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami