apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- $projectName := hasSuffix "-stage" .Release.Name | ternary (trimSuffix "-stage" .Release.Name) (trimSuffix "-prod" .Release.Name) }}
  {{- $bucketSubPath := hasSuffix "-stage" .Release.Name | ternary "/stage" "" }}
  {{- if .Values.app.homeUrl }}
  WP_HOME: {{ .Values.app.homeUrl }}
  {{- else }}
  WP_HOME: https://{{ .Values.ingress.hostname }}
  {{- end }}
  {{- if .Values.app.siteUrl }}
  WP_SITEURL: {{ .Values.app.siteUrl }}
  {{- end }}
  ENVIRONMENT: {{ .Values.app.environment }}
  DEBUG: {{ .Values.app.debug }}
  WP_CACHE: {{ .Values.app.cache }}
  AUTH_KEY: {{ required "AUTH_KEY" .Values.app.authKey }}
  SECURE_AUTH_KEY: {{ required "SECURE_AUTH_KEY" .Values.app.secureAuthKey }}
  LOGGED_IN_KEY: {{ required "LOGGED_IN_KEY" .Values.app.loggedInKey }}
  NONCE_KEY: {{ required "NONCE_KEY" .Values.app.nonceKey }}
  AUTH_SALT: {{ required "AUTH_SALT" .Values.app.authSalt }}
  SECURE_AUTH_SALT: {{ required "SECURE_AUTH_SALT" .Values.app.secureAuthSalt }}
  LOGGED_IN_SALT: {{ required "LOGGED_IN_SALT" .Values.app.loggedInSalt }}
  NONCE_SALT: {{ required "NONCE_SALT" .Values.app.nonceSalt }}
  MAIL_FROM_NAME: {{ required "MAIL_FROM_NAME" .Values.app.mailFromName }}
  {{- if .Values.app.dbName }}
  DB_NAME: {{ .Values.app.dbName }}
  {{- else }}
  DB_NAME: {{ $projectName }}
  {{- end }}
  {{- if .Values.app.dbUser }}
  DB_USER: {{ .Values.app.dbUser }}
  {{- else }}
  DB_USER: {{ $projectName }}
  {{- end }}
  {{- if .Values.app.s3UploadsBucket }}
  S3_UPLOADS_BUCKET: {{ .Values.app.s3UploadsBucket }}
  {{- else }}
  S3_UPLOADS_BUCKET: media.wpd.digital/{{ $projectName }}{{ $bucketSubPath }}
  {{- end }}
  {{- if .Values.app.s3UploadsBucketUrl }}
  S3_UPLOADS_BUCKET_URL: {{ .Values.app.s3UploadsBucketUrl }}
  {{- else }}
  S3_UPLOADS_BUCKET_URL: https://media.wpd.digital/{{ $projectName }}{{ $bucketSubPath }}
  {{- end }}
  {{- include "wp-project-skeleton.awsRegion" (list "S3_UPLOADS_REGION" .Values.app.s3UploadsRegion) }}
  {{- if .Values.app.redisHost }}
  WP_REDIS_HOST: {{ .Values.app.redisHost }}
  {{- else }}
  WP_REDIS_HOST: {{ .Release.Name }}-redis-master
  {{- end }}
  {{- if .Values.app.redisPrefix }}
  WP_REDIS_PREFIX: {{ .Values.app.redisPrefix }}
  {{- else }}
  WP_REDIS_PREFIX: {{ .Release.Name }}
  {{- end }}
  {{- if .Values.app.cdnDomain }}
  CDN_DOMAIN: {{ .Values.app.cdnDomain }}
  {{- else }}
  CDN_DOMAIN: {{ hasSuffix "-stage" .Release.Name | ternary .Release.Name (trimSuffix "-prod" .Release.Name) }}.wpd.digital
  {{- end }}
  {{- if .Values.app.newrelicDaemonAddress }}
  NEWRELIC_DAEMON_ADDRESS: {{ .Values.app.newrelicDaemonAddress }}
  {{- else }}
  NEWRELIC_DAEMON_ADDRESS: "{{ .Release.Name }}-newrelic-php-agent:{{ index .Values "newrelic-php-agent" "service" "port" }}"
  {{- end }}
  {{- if .Values.app.newrelicLicense }}
  {{- end }}
  {{- if .Values.app.newrelicAppName }}
  {{- end }}
  {{- if .Values.app.inncognitoDomain }}
  INNCOGNITO_DOMAIN: {{ .Values.app.inncognitoDomain }}
  {{- include "wp-project-skeleton.awsRegion" (list "INNCOGNITO_REGION" .Values.app.inncognitoRegion) }}
  {{- if .Values.app.inncognitoRedirectUri }}
  INNCOGNITO_REDIRECT_URI: {{ .Values.app.inncognitoRedirectUri }}
  {{- end }}
  {{- if .Values.app.inncognitoForceCognito }}
  INNCOGNITO_FORCE_COGNITO: {{ .Values.app.inncognitoForceCognito }}
  {{- end }}
  {{- end }}
  {{- include "wp-project-skeleton.awsRegion" (list "AWS_LAMBDA_IMAGE_REGION" .Values.app.awsLambdaImageRegion) }}
  {{- if .Values.app.awsLambdaImageFunction }}
  AWS_LAMBDA_IMAGE_FUNCTION: {{ .Values.app.awsLambdaImageFunction }}
  {{- end }}
  {{- include "wp-project-skeleton.awsRegion" (list "AWS_LAMBDA_CRITICAL_CSS_REGION" .Values.app.awsLambdaCriticalCssRegion) }}
  {{- include "wp-project-skeleton.awsRegion" (list "AWS_LAMBDA_PRERENDER_REGION" .Values.app.awsLambdaPrerenderRegion) }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
