apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- include "common.tplvalues.render" (dict "value" .Values.imagePullSecrets "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "wp-project-skeleton.image" . }}
          imagePullPolicy: {{- include "common.tplvalues.render" (dict "value" .Values.image.pullPolicy "context" $) }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" }}-env
            - secretRef:
                name: {{ include "common.names.fullname" }}-secret
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp -r /usr/src/html/. /var/www/html/
                    chown -R www-data:www-data /var/www/html
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 30
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /var/www/html
              name: {{ .Chart.Name }}-data
        - name: {{ .Chart.Name }}-nginx
          image: {{ include "wp-project-skeleton.nginx.image" . }}
          imagePullPolicy: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.image.pullPolicy "context" $) }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- if .Values.nginx.resources }}
          resources: {{- toYaml .Values.nginx.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /var/www/html
              name: {{ .Chart.Name }}-data
            - mountPath: /etc/nginx/conf.d/default.conf
              name: {{ .Chart.Name }}-nginx-config
              subPath: default.conf
      volumes:
        - name: {{ .Chart.Name }}-data
          emptyDir: {}
        - name: {{ .Chart.Name }}-nginx-config
            configMap:
                name: {{ include "common.names.fullname" }}-nginx-config
                items:
                - key: default.conf
                  path: default.conf
